# Example R Markdown File
## from "Reproducible Research with R and RStudio"
### Christopher Gandrud
### 15 January 2015

-----------

```{r LoadPackages, include=FALSE}
# Load required packages
library(devtools)
```

We can use the [googleVis](http://code.google.com/p/google-motion-charts-with-r/) 
package to create interactive JavaScript tables, charts, and maps. Here is an 
example of how to create a map with *googleVis*'s `gvisGeoChart` function. 

Let's first download some data from [GitHub](https://github.com/). See chapters 
6 and 7 for details about this data as well as the 
[variable description page](https://github.com/christophergandrud/Rep-Res-Examples/blob/master/DataGather_Merge/MainData_VariableDescriptions.md).

-----------

## Fertilizer Consumption (kilograms per hectare of arable land) in 2003
### Data from [World Bank](http://data.worldbank.org/indicator/AG.CON.FERT.ZS)

```{r CreategvisGeoChart, echo=FALSE, message=FALSE, results='asis'}
# Create geo map of global fertilizer consumption for 2003
# The data is loaded from GitHub (http://bit.ly/V0ldsf)
## The data gathering process used to create this data set
## is completely reproducible. For more information see:
## http://bit.ly/YnMKBG
source_url("http://bit.ly/VNnZxS")
```

-----------

